services:
  postgres:
    image: postgres:17.2-alpine3.21
    env_file:
      - .env
    ports:
      - "5432:5432"
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file: .env